### ISSUE TITLE
Idea: simple way to enable/disable a service

### ISSUE THREAD

**Issue by yscialom** [yscialom/pinanas#20]

**Comment by yscialom** [comment]
A mon avis, tu sur-estimes la complexité des templates ansible, ou tu sous-estimes ta capacité à les utiliser.

Test: https://ansible.sivel.net/test/

### Variables
```yaml
pinanas:
  services:
    - adguardhome
    - jellyfin
    #- nextcloud
```

### Template
```yaml
services:
{% if 'adguardhome' in pinanas.services %}
  adguardhome:
    image: ...
{% endif %}

{% if 'jellyfin' in pinanas.services %}
  jellyfin:
    image: ...
{% endif %}

{% if 'nextcloud' in pinanas.services %}
  nextcloud:
    image: ...
{% endif %}
```

### Rendered
```yaml
services:
  adguardhome:
    image: ...

  jellyfin:
    image: ...
```
