### ISSUE TITLE
Nextcloud only works if installation directory is named "pinanas"

### ISSUE THREAD

**Issue by yscialom** [yscialom/pinanas#59]
From docker-compose:
```
nextcloud:
    build:
      context: nextcloud/build
    #[...]
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=pinanas_default"
```

The thing is the default network is only named `pinanas_default` when the installation directory is named `pinanas`.

A name could be given to docker-compose default network by replacing
```yaml
networks:
  default:
```
by
```yaml
networks:
  default:
    name: pinanas_default
```

But this requires docker-compose file version 3.5+ and docker-compose v1.27+. The thing is, only docker-compose v1.25 is available in default repositories of Debian and Ubuntu :(
