### ISSUE TITLE
Defaut settings - DHCP range not finded

### ISSUE THREAD

**Issue by glevil** [yscialom/pinanas#70]
Commit 69a981444f4dc30dccc96744ccb38c8f9db4f3e8 (develop)
Error during ansible playbook step with configure.sh : doesn't get the ip range variables.

[settings.yml.sample](https://github.com/yscialom/pinanas/blob/develop/src/settings.yml.sample)

```
  network:
    dhcp:
      range:
        # First (included) IP of clients inside the network. Type: string. Default: auto discovery. Example: "192.168.0.16".
        #start:

        # Last (included) IP of clients inside the network. Type: string. Default: auto discovery. Example: "192.168.0.64".
        #end:
```

[default-settings.yml](https://github.com/yscialom/pinanas/blob/develop/src/default-settings.yml)

```
      range:
        # First (included) IP of clients inside the network. Type: string. Example: "192.168.0.16".
        start: "{{ [ ansible_default_ipv4.network, ansible_default_ipv4.netmask ]
          | join('/')
          | ansible.utils.ipaddr('net')
          | ansible.utils.ipaddr('1')
          | ansible.utils.ipaddr('ip') }}"

        # Last (included) IP of clients inside the network. Type: string. Example: "192.168.0.64".
        end: "{{ [ ansible_default_ipv4.network, ansible_default_ipv4.netmask ]
          | join('/')
          | ansible.utils.ipaddr('net')
          | ansible.utils.ipaddr('-1')
          | ansible.utils.ipaddr('ip') }}"
```

Error sent :

> ```
> TASK [create /pinanas/dist/dhcpd/config/dhcpd.conf from settings] **************
> task path: /pinanas/venv/ansible/playbook.yml:135
> <localhost> ESTABLISH LOCAL CONNECTION FOR USER: pinanas
> <localhost> EXEC /bin/sh -c 'echo ~pinanas && sleep 0'
> <localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/pinanas/.ansible/tmp `"&& mkdir "` echo /home/pinanas/.ansible/tmp/ansible-tmp-1669837823.2663186-817-76952560900213 `" && echo ansible-tmp-1669837823.2663186-817-76952560900213="` echo /home/pinanas/.ansible/tmp/ansible-tmp-1669837823.2663186-817-76952560900213 `" ) && sleep 0'
> <localhost> EXEC /bin/sh -c 'rm -f -r /home/pinanas/.ansible/tmp/ansible-tmp-1669837823.2663186-817-76952560900213/ > /dev/null 2>&1 && sleep 0'
> The full traceback is:
> Traceback (most recent call last):
>   File "/pinanas/venv/lib/python3.9/site-packages/ansible/template/__init__.py", line 1160, in do_template
>     res = j2_concat(rf)
>   File "<template>", line 31, in root
>   File "/pinanas/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
>     raise self._undefined_exception(self._undefined_message)
> jinja2.exceptions.UndefinedError: 'None' has no attribute 'start'
> ```
