### ISSUE TITLE
Make configure.sh put VERSION file to the target

### ISSUE THREAD

**Issue by yscialom** [yscialom/pinanas#92]
Source
===
If sources are from a git repository, use git describe (?).
If not, use the VERSION from source to be added.

Content
===
```yaml
version: M.m.p[-n-gsha1]
date: YYYY-mm-dd
dirty: yes|no
```
